import { apiUrl } from "@/lib/api";
import type {
	AdminLectureRecord,
	AdminTokenRecord,
	LectureAdminStats,
	TokenAdminStats,
	UpdateTokenInput,
} from "@/lib/admin";
import type {
	CreateUserInput,
	DashboardStats,
	RecentSessionTopic,
	SessionSummary,
	UpdateUserInput,
	UserRecord,
} from "@/lib/dashboard";
import { authHeaders } from "@/lib/auth";

async function adminJson<T>(path: string, init?: RequestInit): Promise<T> {
	const res = await fetch(apiUrl(path), {
		...init,
		headers: { ...authHeaders(), ...init?.headers },
	});
	const data = (await res.json()) as T & { error?: string };
	if (!res.ok) throw new Error(data.error ?? "Request failed.");
	return data;
}

export async function fetchAdminStats(): Promise<DashboardStats> {
	const data = await adminJson<{ stats: DashboardStats }>("/api/admin/stats");
	return data.stats;
}

export async function fetchAdminRecentSessionTopics(limit = 8): Promise<RecentSessionTopic[]> {
	const data = await adminJson<{ sessions: RecentSessionTopic[] }>(
		`/api/admin/sessions/recent-topics?limit=${limit}`,
	);
	return data.sessions;
}

export async function fetchAdminSession(id: string): Promise<RecentSessionTopic> {
	const data = await adminJson<{ session: RecentSessionTopic }>(`/api/admin/sessions/${id}`);
	return data.session;
}

export async function stopAdminSession(id: string): Promise<RecentSessionTopic> {
	const data = await adminJson<{ session: RecentSessionTopic }>(`/api/admin/sessions/${id}/stop`, {
		method: "POST",
	});
	return data.session;
}

export async function deleteAdminSession(id: string): Promise<void> {
	await adminJson(`/api/admin/sessions/${id}`, { method: "DELETE" });
}

export function exportSessionTopicsCsv(sessions: RecentSessionTopic[]): void {
	const headers = [
		"Topic",
		"Lecture",
		"Generated by",
		"Email",
		"Workflow",
		"Model",
		"State",
		"Messages",
		"Created",
		"Updated",
	];
	const rows = sessions.map((session) => [
		session.topic,
		session.lectureTitle ?? "",
		session.generatedByName ?? "",
		session.generatedByEmail ?? "",
		session.workflow ?? "",
		session.model,
		session.state,
		String(session.messageCount),
		session.createdAt,
		session.updatedAt,
	]);
	const csv = [headers, ...rows]
		.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
		.join("\n");
	const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = `aula-sessions-${new Date().toISOString().slice(0, 10)}.csv`;
	link.click();
	URL.revokeObjectURL(url);
}

export async function fetchAdminSessions(limit = 50): Promise<SessionSummary[]> {
	const data = await adminJson<{ sessions: SessionSummary[] }>(`/api/admin/sessions?limit=${limit}`);
	return data.sessions;
}

export async function fetchAdminUsers(): Promise<UserRecord[]> {
	const data = await adminJson<{ users: UserRecord[] }>("/api/admin/users");
	return data.users;
}

export async function createAdminUser(input: CreateUserInput & { password?: string }): Promise<UserRecord> {
	const data = await adminJson<{ user: UserRecord }>("/api/admin/users", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user;
}

export async function updateAdminUser(id: string, input: UpdateUserInput): Promise<UserRecord> {
	const data = await adminJson<{ user: UserRecord }>(`/api/admin/users/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user;
}

export async function deleteAdminUser(id: string): Promise<void> {
	await adminJson(`/api/admin/users/${id}`, { method: "DELETE" });
}

export async function resetAdminUserPassword(id: string, password: string): Promise<void> {
	await adminJson(`/api/admin/users/${id}/reset-password`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ password }),
	});
}

export async function bulkAdminUserStatus(ids: string[], status: "active" | "inactive"): Promise<number> {
	const data = await adminJson<{ updated: number }>("/api/admin/users/bulk-status", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids, status }),
	});
	return data.updated;
}

export async function bulkAdminDeleteUsers(ids: string[]): Promise<number> {
	const data = await adminJson<{ deleted: number }>("/api/admin/users/bulk-delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.deleted;
}

export async function fetchAdminLectures(): Promise<{
	lectures: AdminLectureRecord[];
	stats: LectureAdminStats;
}> {
	const data = await adminJson<{
		lectures: AdminLectureRecord[];
		stats: LectureAdminStats;
	}>("/api/admin/lectures");
	return { lectures: data.lectures ?? [], stats: data.stats! };
}

export async function deleteAdminLecture(id: string): Promise<void> {
	await adminJson(`/api/admin/lectures/${id}`, { method: "DELETE" });
}

export async function fetchAdminTokens(): Promise<{
	users: AdminTokenRecord[];
	stats: TokenAdminStats;
}> {
	const data = await adminJson<{
		users: AdminTokenRecord[];
		stats: TokenAdminStats;
	}>("/api/admin/tokens");
	return { users: data.users ?? [], stats: data.stats! };
}

export async function updateAdminTokens(
	userId: string,
	input: UpdateTokenInput,
): Promise<AdminTokenRecord> {
	const data = await adminJson<{ user: AdminTokenRecord }>(`/api/admin/tokens/${userId}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user!;
}

export async function bulkAdminResetTokens(ids: string[]): Promise<number> {
	const data = await adminJson<{ reset: number }>("/api/admin/tokens/bulk-reset", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.reset;
}

export function exportUsersCsv(users: UserRecord[]): void {
	const headers = ["Name", "Email", "Role", "Status", "Department", "Institution", "Last Active", "Joined"];
	const rows = users.map((user) => [
		user.name,
		user.email,
		user.role,
		user.status,
		user.department ?? "",
		user.institution ?? "",
		user.lastActiveAt ?? "",
		user.createdAt,
	]);
	const csv = [headers, ...rows]
		.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
		.join("\n");
	const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = `aula-users-${new Date().toISOString().slice(0, 10)}.csv`;
	link.click();
	URL.revokeObjectURL(url);
}
