"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import { AdminDataTable } from "@/components/admin/AdminDataTable";
import {
	AdminPanel,
	AdminShell,
	AdminStatCard,
	formatAdminDate,
	formatAdminRelative,
	formatSessionTopic,
	isSessionTopicTruncated,
} from "@/components/admin/AdminShell";
import { AdminSessionRowActions } from "@/components/admin/AdminSessionRowActions";
import { useAdminGuard } from "@/hooks/useAdminGuard";
import { useAdminTable } from "@/hooks/useAdminTable";
import { exportSessionTopicsCsv, fetchAdminSessions } from "@/lib/admin-api";
import type { RecentSessionTopic, SessionSummary } from "@/lib/dashboard";

function toRecentSession(session: SessionSummary): RecentSessionTopic {
	return {
		id: session.id,
		topic: session.topic?.trim() || session.workflow?.trim() || "General research",
		workflow: session.workflow,
		model: session.model,
		state: session.state,
		messageCount: session.messageCount,
		lectureTitle: session.lectureTitle,
		generatedByName: session.generatedByName,
		generatedByEmail: session.generatedByEmail,
		createdAt: session.createdAt,
		updatedAt: session.updatedAt,
	};
}

export function AdminSessionsDashboard() {
	const { ready } = useAdminGuard();
	const [sessions, setSessions] = useState<SessionSummary[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);
	const [search, setSearch] = useState("");
	const [stateFilter, setStateFilter] = useState("all");

	const load = useCallback(async () => {
		setError(null);
		try {
			const data = await fetchAdminSessions(100);
			setSessions(data);
		} catch (err) {
			setError(err instanceof Error ? err.message : String(err));
		} finally {
			setLoading(false);
		}
	}, []);

	useEffect(() => {
		if (ready) void load();
	}, [load, ready]);

	const states = useMemo(() => {
		const unique = new Set(sessions.map((s) => s.state));
		return Array.from(unique).sort();
	}, [sessions]);

	const query = search.trim().toLowerCase();
	const filtered = useMemo(() => {
		return sessions.filter((session) => {
			if (stateFilter !== "all" && session.state !== stateFilter) return false;
			if (!query) return true;
			return (
				(session.topic?.toLowerCase().includes(query) ?? false) ||
				(session.workflow?.toLowerCase().includes(query) ?? false) ||
				session.model.toLowerCase().includes(query) ||
				session.state.toLowerCase().includes(query) ||
				(session.lectureTitle?.toLowerCase().includes(query) ?? false) ||
				(session.generatedByName?.toLowerCase().includes(query) ?? false) ||
				(session.generatedByEmail?.toLowerCase().includes(query) ?? false)
			);
		});
	}, [sessions, stateFilter, query]);

	const { pageItems, pagination } = useAdminTable(filtered, { resetDeps: [query, stateFilter] });

	const runningCount = sessions.filter((s) => s.state === "running" || s.state === "starting").length;
	const totalMessages = sessions.reduce((sum, s) => sum + s.messageCount, 0);

	const columns = useMemo(
		() => [
			{
				key: "topic",
				header: "Topic / workflow",
				cell: (session: SessionSummary) => {
					const topicLabel =
						session.topic?.trim() || session.workflow?.trim() || "General research";
					return (
						<>
							<span
								className="admin-cell-name"
								title={isSessionTopicTruncated(topicLabel) ? topicLabel : undefined}
							>
								{formatSessionTopic(topicLabel)}
							</span>
							{session.workflow && session.topic && (
								<span className="admin-cell-sub">/{session.workflow}</span>
							)}
						</>
					);
				},
			},
			{
				key: "lecture",
				header: "Lecture",
				cell: (session: SessionSummary) =>
					session.lectureTitle ? (
						<span
							className="admin-cell-name"
							title={
								isSessionTopicTruncated(session.lectureTitle)
									? session.lectureTitle
									: undefined
							}
						>
							{formatSessionTopic(session.lectureTitle)}
						</span>
					) : (
						<span className="muted">—</span>
					),
			},
			{
				key: "generatedBy",
				header: "Generated by",
				cell: (session: SessionSummary) =>
					session.generatedByName ? (
						<>
							<span className="admin-cell-name">{session.generatedByName}</span>
							{session.generatedByEmail && (
								<span className="admin-cell-sub">{session.generatedByEmail}</span>
							)}
						</>
					) : (
						<span className="muted">—</span>
					),
			},
			{
				key: "model",
				header: "Model",
				cell: (session: SessionSummary) => (
					<span className="dash-mono">{session.model}</span>
				),
			},
			{
				key: "state",
				header: "State",
				cell: (session: SessionSummary) => (
					<span className={`dash-badge dash-badge-state-${session.state}`}>
						{session.state}
					</span>
				),
			},
			{
				key: "messages",
				header: "Messages",
				cell: (session: SessionSummary) => session.messageCount,
				align: "center" as const,
			},
			{
				key: "created",
				header: "Created",
				cell: (session: SessionSummary) => (
					<span className="muted">{formatAdminDate(session.createdAt)}</span>
				),
			},
			{
				key: "updated",
				header: "Updated",
				cell: (session: SessionSummary) => (
					<span className="muted" title={formatAdminDate(session.updatedAt)}>
						{formatAdminRelative(session.updatedAt)}
					</span>
				),
			},
			{
				key: "actions",
				header: "",
				align: "right" as const,
				cell: (session: SessionSummary) => (
					<AdminSessionRowActions
						session={toRecentSession(session)}
						onChange={() => void load()}
						compact
					/>
				),
			},
		],
		[load],
	);

	return (
		<AdminShell
			title="Sessions"
			subtitle="Monitor research sessions across all users"
			breadcrumb="Admin Console"
		>
			{loading && <p className="muted">Loading sessions…</p>}
			{error && <div className="banner banner-error">{error}</div>}

			<section className="admin-stats">
				<AdminStatCard label="Total sessions" value={sessions.length} accent="primary" />
				<AdminStatCard
					label="Live now"
					value={runningCount}
					accent={runningCount > 0 ? "warning" : undefined}
				/>
				<AdminStatCard label="Messages (shown)" value={totalMessages} hint="In loaded sessions" />
			</section>

			<AdminPanel
				title="All sessions"
				description={`${filtered.length.toLocaleString()} of ${sessions.length.toLocaleString()} sessions`}
				actions={
					<>
						<button
							type="button"
							className="ghost-btn"
							onClick={() => exportSessionTopicsCsv(filtered.map(toRecentSession))}
							disabled={filtered.length === 0}
						>
							Export
						</button>
						<button type="button" className="ghost-btn" onClick={() => void load()}>
							Refresh
						</button>
					</>
				}
			>
				<AdminDataTable
					columns={columns}
					data={pageItems}
					rowKey={(session) => session.id}
					loading={loading}
					search={search}
					onSearchChange={setSearch}
					searchPlaceholder="Search topic, workflow, model…"
					hasActiveFilters={Boolean(query) || stateFilter !== "all"}
					emptyMessage="No sessions yet."
					emptyFilteredMessage="No sessions match your filters."
					filters={
						<select
							className="topic-input admin-toolbar-select"
							value={stateFilter}
							onChange={(e) => setStateFilter(e.target.value)}
							aria-label="Filter by state"
						>
							<option value="all">All states</option>
							{states.map((state) => (
								<option key={state} value={state}>
									{state}
								</option>
							))}
						</select>
					}
					pagination={pagination}
				/>
			</AdminPanel>
		</AdminShell>
	);
}
