"use client";

import { formatAdminDate } from "@/components/admin/AdminShell";
import type { RecentSessionTopic } from "@/lib/dashboard";

type Props = {
	session: RecentSessionTopic;
	onClose: () => void;
};

function DetailRow({ label, value }: { label: string; value: string }) {
	return (
		<div className="admin-session-detail-row">
			<span className="admin-session-detail-label">{label}</span>
			<span className="admin-session-detail-value">{value}</span>
		</div>
	);
}

export function AdminSessionDetailModal({ session, onClose }: Props) {
	return (
		<div className="modal-backdrop" onClick={onClose}>
			<div className="modal dash-modal admin-session-modal" onClick={(e) => e.stopPropagation()}>
				<div className="modal-header">
					<h3>Session details</h3>
					<button type="button" className="icon-btn" onClick={onClose} aria-label="Close">
						×
					</button>
				</div>
				<div className="admin-session-detail">
					<p className="admin-session-detail-topic">{session.topic}</p>
					<DetailRow label="Lecture" value={session.lectureTitle ?? "—"} />
					<DetailRow
						label="Generated by"
						value={
							session.generatedByName
								? session.generatedByEmail
									? `${session.generatedByName} (${session.generatedByEmail})`
									: session.generatedByName
								: "—"
						}
					/>
					<DetailRow label="Session ID" value={session.id} />
					<DetailRow label="Workflow" value={session.workflow ?? "—"} />
					<DetailRow label="Model" value={session.model} />
					<DetailRow
						label="State"
						value={session.state.charAt(0).toUpperCase() + session.state.slice(1)}
					/>
					<DetailRow label="Messages" value={session.messageCount.toLocaleString()} />
					<DetailRow label="Created" value={formatAdminDate(session.createdAt)} />
					<DetailRow label="Last updated" value={formatAdminDate(session.updatedAt)} />
				</div>
				<div className="dash-form-actions admin-session-detail-actions">
					<button type="button" className="primary-btn" onClick={onClose}>
						Close
					</button>
				</div>
			</div>
		</div>
	);
}
